[wokwi]
version = 1
rfc2217ServerPort = 4001
firmware = '.pio/build/esp32dev/firmware.bin'
elf = '.pio/build/esp32dev/firmware.elf'

# Causal system models: network, radio and traffic.

# Signal-generating subsystem models (no direct-value sliders).
[[chip]]
name = 'traffic-pulse-generator'
binary = 'dist/traffic-pulse-generator.chip.wasm'

[[chip]]
name = 'backhaul-packet-emulator'
binary = 'dist/backhaul-packet-emulator.chip.wasm'

[[chip]]
name = 'radio-signal-generator'
binary = 'dist/radio-signal-generator.chip.wasm'
